### ISSUE TITLE
Github link should link to the toolbox

### ISSUE THREAD

**Issue by BlitzOffline** [HelpChat/toolbox#39]
Right now, there is a Github button but it links to github.com/HelpChat. It would be nice if instead it would link directly to the toolbox. This could potentially bring some extra help or at least some extra interest in this repository. There's no reason to link the github org since they can just see what org the repository is in if that's what they want.

**Comment by darbyjack** [comment]
Fixed via https://github.com/HelpChat/toolbox/commit/ec1f4a4882f7540bc0c589e90a8d6f78691d5552
