### ISSUE TITLE
More accessible back button on each tools page

### ISSUE THREAD

**Issue by Aberdeener** [HelpChat/toolbox#5]
Although it is possible to go back by clicking on the logo in the top left, this is a bit of a reach when the main content is in the middle of the page.
There is decent space around this area of the site, a simple "Back" button, or pointy back arrow button here could just do the trick.
<img width="1031" alt="Screen Shot 2022-04-05 at 08 47 40" src="https://user-images.githubusercontent.com/26070412/161793791-95ee93b7-5fe8-4444-aa9b-bd8482565ae0.png">

**Comment by Funny-cube** [comment]
Hey,

So there's actually already two ways to get back. One as mentioned, clicking the logo and another is the 'Home' option in the nav bar. If we added a 'Back' button It may seem a little unintuitive to have three ways to get back to the same page.
